### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/minoshirokin#1]
- [ ] Implement all customization settings
- [ ] Put a link to download file
- [ ] Improve colors and backgrounds
  - [x] Allow dark background colors (and adapt text to it)
  - [ ] Use generated textures as backgrounds

By the way: how to handle version numbers?
